export const MUNICIPALITY_LINKS = {
  // ── 石川県 ─────────────────────────────────────────────────────────────────
  '17201': {
    city: '金沢市', pref: '石川県',
    officialSite: 'https://www4.city.kanazawa.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: 'https://www4.city.kanazawa.lg.jp/soshikikarasagasu/kenchikushidoka/gyomuannai/2_2/8494.html', supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: 'https://www4.city.kanazawa.lg.jp/soshikikarasagasu/toshikeikakuka/gyomuannai/1/1/2/kanazawatoshikeikakunogaiyo/24803.html', supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www4.city.kanazawa.lg.jp/kurashi_tetsuzuki/anzen_anshin/bosai/2/6/15696.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: 'https://www4.city.kanazawa.lg.jp/soshikikarasagasu/toshikeikakuka/gyomuannai/1/1/2/totiriyo/4565.html', supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: 'https://www4.city.kanazawa.lg.jp/kurashi_tetsuzuki/jogesuido/index.html', supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: 'https://www4.city.kanazawa.lg.jp/soshikikarasagasu/bunkazaihogoka/gyomuannai/3/1/3/9171.html', supportsLatLng: false, supportsAddress: false },
    },
  },
  '17205': {
    city: '小松市', pref: '石川県',
    officialSite: 'https://www.city.komatsu.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: 'https://www.city.komatsu.lg.jp/soshiki/kenchikujuutaku/kenchiku/2194.html', supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: 'https://www.city.komatsu.lg.jp/soshiki/1022/toshi_chikukeikaku/2123.html', supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.komatsu.lg.jp/soshiki/1007/kakushuhaza_domappu/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: 'https://www.city.komatsu.lg.jp/soshiki/1022/toshi_chikukeikaku/2123.html', supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: 'https://www.city.komatsu.lg.jp/kurasi_tetuzuki/jogesuido/index.html', supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: 'https://www.city.komatsu.lg.jp/soshiki/1052/maizoubunkazainotoriatsukainikansurukoto/kaihatsukyogikankei_tetsuzuki/1595.html', supportsLatLng: false, supportsAddress: false },
    },
  },
  '17206': {
    city: '加賀市', pref: '石川県',
    officialSite: 'https://www.city.kaga.ishikawa.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: 'https://www.city.kaga.ishikawa.jp/soshiki/kensetsu/kenchiku_shido/2/1743.html', supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: 'https://www.city.kaga.ishikawa.jp/soshiki/kensetsu/toshi_keikaku/7/2/786.html', supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kaga.ishikawa.jp/kurashi/bosai/map/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: 'https://www.city.kaga.ishikawa.jp/soshiki/kensetsu/toshi_keikaku/7/2/786.html', supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: 'https://www.city.kaga.ishikawa.jp/soshiki/jogesuido/index.html', supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: 'https://www.city.kaga.ishikawa.jp/ed/bunka_shinko/600.html', supportsLatLng: false, supportsAddress: false },
    },
  },
  '17209': {
    city: '白山市', pref: '石川県',
    officialSite: 'https://www.city.hakusan.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: 'https://www.city.hakusan.lg.jp/machi/toshikeikaku/1002974.html', supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.hakusan.lg.jp/seikatsu/bosai/1004660/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: 'https://www.city.hakusan.lg.jp/machi/toshikeikaku/1002974.html', supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: 'https://www.city.hakusan.lg.jp/seikatsu/suido/index.html', supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: 'https://www.city.hakusan.lg.jp/bunka/bunkazai/1002265.html', supportsLatLng: false, supportsAddress: false },
    },
  },
  '17210': {
    city: '能美市', pref: '石川県',
    officialSite: 'https://www.city.nomi.ishikawa.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: 'https://www.city.nomi.ishikawa.jp/www/genre/1000100000170/index.html', supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.nomi.ishikawa.jp/hazardmap/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: 'https://www.city.nomi.ishikawa.jp/www/contents/1001000000974/index.html', supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: 'https://www.city.nomi.ishikawa.jp/www/section/1552889134579/index.html', supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: 'https://www.city.nomi.ishikawa.jp/www/contents/1001000000850/index.html', supportsLatLng: false, supportsAddress: false },
    },
  },
  '17211': {
    city: '野々市市', pref: '石川県',
    officialSite: 'https://www.city.nonoichi.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: 'https://www.city.nonoichi.lg.jp/soshiki/29/48334.html', supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: 'https://www.city.nonoichi.lg.jp/soshiki/31/1649.html', supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.nonoichi.lg.jp/bosai/hazardmap/flow_01.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: 'https://www.city.nonoichi.lg.jp/soshiki/30/695.html', supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: 'https://www.city.nonoichi.lg.jp/soshiki/32/', supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: 'https://www.city.nonoichi.lg.jp/soshiki/40/2518.html', supportsLatLng: false, supportsAddress: false },
    },
  },

  // ── 東京23区 ───────────────────────────────────────────────────────────────
  '13101': {
    city: '千代田区', pref: '東京都',
    officialSite: 'https://www.city.chiyoda.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.chiyoda.lg.jp/koho/kurashi/bosai/bosai-taisaku/fusui-dosha-saigai/map.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13102': {
    city: '中央区', pref: '東京都',
    officialSite: 'https://www.city.chuo.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.chuo.lg.jp/bousaianzen/bousai/bousaitaisaku/suigaisonae/kouzuihazardmap/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13103': {
    city: '港区', pref: '東京都',
    officialSite: 'https://www.city.minato.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.minato.tokyo.jp/dobokukeikaku/bosai-anzen/bosai/shinsui/hazard-map/', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13104': {
    city: '新宿区', pref: '東京都',
    officialSite: 'https://www.city.shinjuku.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.shinjuku.lg.jp/anzen/file03_00016.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13105': {
    city: '文京区', pref: '東京都',
    officialSite: 'https://www.city.bunkyo.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.bunkyo.lg.jp/bousaianzen/bousai/kinkyuusaigai/map/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13106': {
    city: '台東区', pref: '東京都',
    officialSite: 'https://www.city.taito.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.taito.lg.jp/bosai/map/saigai/hazardmap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13107': {
    city: '墨田区', pref: '東京都',
    officialSite: 'https://www.city.sumida.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.sumida.lg.jp/anzen_anshin/bousai/suigai/suigai.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13108': {
    city: '江東区', pref: '東京都',
    officialSite: 'https://www.city.koto.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.koto.lg.jp/470601/20200701.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13109': {
    city: '品川区', pref: '東京都',
    officialSite: 'https://www.city.shinagawa.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.shinagawa.tokyo.jp/PC/bosai/bosai2/panfu/map/hpg000022947.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13110': {
    city: '目黒区', pref: '東京都',
    officialSite: 'https://www.city.meguro.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.meguro.tokyo.jp/bousai/bousaianzen/bousai/map.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13111': {
    city: '大田区', pref: '東京都',
    officialSite: 'https://www.city.ota.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.ota.tokyo.jp/shisetsu/map/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13112': {
    city: '世田谷区', pref: '東京都',
    officialSite: 'https://www.city.setagaya.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.setagaya.lg.jp/02049/606.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13113': {
    city: '渋谷区', pref: '東京都',
    officialSite: 'https://www.city.shibuya.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.shibuya.tokyo.jp/bosai/bosai/bosai-manual-map/kozui_map.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13114': {
    city: '中野区', pref: '東京都',
    officialSite: 'https://www.city.tokyo-nakano.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.tokyo-nakano.lg.jp/bosai/hazardmap/hazardmap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13115': {
    city: '杉並区', pref: '東京都',
    officialSite: 'https://www.city.suginami.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.suginami.tokyo.jp/bousai/bousai/hazardmap/kouzui/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13116': {
    city: '豊島区', pref: '東京都',
    officialSite: 'https://www.city.toshima.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.toshima.lg.jp/bosai/taisaku/hazard-map/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13117': {
    city: '北区', pref: '東京都',
    officialSite: 'https://www.city.kita.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kita.tokyo.jp/bosai/bosai/documents/documents/documents/hazardmap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13118': {
    city: '荒川区', pref: '東京都',
    officialSite: 'https://www.city.arakawa.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.arakawa.tokyo.jp/a013/bousai/suigainisonaete/suigaimap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13119': {
    city: '板橋区', pref: '東京都',
    officialSite: 'https://www.city.itabashi.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.itabashi.tokyo.jp/bousai/bousai/map/1005633.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13120': {
    city: '練馬区', pref: '東京都',
    officialSite: 'https://www.city.nerima.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.nerima.tokyo.jp/kurashi/bosai/suigai/hazardmap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13121': {
    city: '足立区', pref: '東京都',
    officialSite: 'https://www.city.adachi.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.adachi.tokyo.jp/kikaku/bosai/bosai/hazard-map-k.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13122': {
    city: '葛飾区', pref: '東京都',
    officialSite: 'https://www.city.katsushika.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.katsushika.lg.jp/kurashi/1004028/1000063/1004031/1022522.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '13123': {
    city: '江戸川区', pref: '東京都',
    officialSite: 'https://www.city.edogawa.tokyo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.edogawa.tokyo.jp/e007/bosaianzen/bosai/kanrenmap/hazardmap/5-1gaiyouban/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },

  // ── 東京圏（政令市） ────────────────────────────────────────────────────────
  '11100': {
    city: 'さいたま市', pref: '埼玉県',
    officialSite: 'https://www.city.saitama.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.saitama.lg.jp/001/011/015/002/003/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '12100': {
    city: '千葉市', pref: '千葉県',
    officialSite: 'https://www.city.chiba.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.chiba.jp/other/jf_hazardmap/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '14100': {
    city: '横浜市', pref: '神奈川県',
    officialSite: 'https://www.city.yokohama.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.yokohama.lg.jp/bousai-kyukyu-bohan/bousai-saigai/map/flood-hmap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '14130': {
    city: '川崎市', pref: '神奈川県',
    officialSite: 'https://www.city.kawasaki.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kawasaki.jp/530/page/0000018174.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },

  // ── 大阪圏 ─────────────────────────────────────────────────────────────────
  '27100': {
    city: '大阪市', pref: '大阪府',
    officialSite: 'https://www.city.osaka.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.osaka.lg.jp/kikikanrishitsu/page/0000299877.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '27140': {
    city: '堺市', pref: '大阪府',
    officialSite: 'https://www.city.sakai.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.sakai.lg.jp/kurashi/bosai/kangaeru/pamphlet/bosai/bosaimap23/hazardmap.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '27225': {
    city: '東大阪市', pref: '大阪府',
    officialSite: 'https://www.city.higashiosaka.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.higashiosaka.lg.jp/kikikanri/0000030406.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '27203': {
    city: '豊中市', pref: '大阪府',
    officialSite: 'https://www.city.toyonaka.osaka.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.toyonaka.osaka.jp/kurashi/bosai/bousai_info/hazardmap/sinsuiHM.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '27205': {
    city: '吹田市', pref: '大阪府',
    officialSite: 'https://www.city.suita.osaka.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.suita.osaka.jp/anzen/1017894/1017896/1017898/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },

  // ── 名古屋圏 ───────────────────────────────────────────────────────────────
  '23100': {
    city: '名古屋市', pref: '愛知県',
    officialSite: 'https://www.city.nagoya.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.nagoya.jp/bousaiportal/hazardmap/1036428.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '23211': {
    city: '豊田市', pref: '愛知県',
    officialSite: 'https://www.city.toyota.aichi.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.toyota.aichi.jp/kurashi/bousaibouhan/1031852/1029984/1002342.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '23202': {
    city: '岡崎市', pref: '愛知県',
    officialSite: 'https://www.city.okazaki.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.okazaki.lg.jp/shisei/machi/1003096/1012416/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '23203': {
    city: '一宮市', pref: '愛知県',
    officialSite: 'https://www.city.ichinomiya.aichi.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.ichinomiya.aichi.jp/kurashi/saigai/1044519/1046093/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '23206': {
    city: '春日井市', pref: '愛知県',
    officialSite: 'https://www.city.kasugai.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kasugai.lg.jp/shisei/machi/haisui/hazardmap/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },

  // ── 福岡圏 ─────────────────────────────────────────────────────────────────
  '40130': {
    city: '福岡市', pref: '福岡県',
    officialSite: 'https://www.city.fukuoka.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://webmap.city.fukuoka.lg.jp/bousai/', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '40100': {
    city: '北九州市', pref: '福岡県',
    officialSite: 'https://www.city.kitakyushu.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kitakyushu.lg.jp/contents/13801096.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '40203': {
    city: '久留米市', pref: '福岡県',
    officialSite: 'https://www.city.kurume.fukuoka.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kurume.fukuoka.jp/1050kurashi/2040bousaianzen/3003shiru/2023-0908-1436-87.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '40218': {
    city: '春日市', pref: '福岡県',
    officialSite: 'https://www.city.kasuga.fukuoka.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kasuga.fukuoka.jp/kurashi/anzen/bousai/1001398/index.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '40219': {
    city: '大野城市', pref: '福岡県',
    officialSite: 'https://www.city.onojo.fukuoka.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.onojo.fukuoka.jp/s058/030/010/020/010/9021.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },

  // ── 札幌圏 ─────────────────────────────────────────────────────────────────
  '01100': {
    city: '札幌市', pref: '北海道',
    officialSite: 'https://www.city.sapporo.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.sapporo.jp/kikikanri/higoro/fuusui/ssh_map.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '01217': {
    city: '江別市', pref: '北海道',
    officialSite: 'https://www.city.ebetsu.hokkaido.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.ebetsu.hokkaido.jp/site/bousai/272.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '01234': {
    city: '北広島市', pref: '北海道',
    officialSite: 'https://www.city.kitahiroshima.hokkaido.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.kitahiroshima.hokkaido.jp/bousai_map/', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '01203': {
    city: '小樽市', pref: '北海道',
    officialSite: 'https://www.city.otaru.lg.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.otaru.lg.jp/categories/bunya/ansin_anzen/bousai/hazardmap/', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
  '01235': {
    city: '石狩市', pref: '北海道',
    officialSite: 'https://www.city.ishikari.hokkaido.jp',
    links: {
      roadMap:        { label: '指定道路図',      url: null, supportsLatLng: false, supportsAddress: false },
      cityPlanMap:    { label: '都市計画図',       url: null, supportsLatLng: false, supportsAddress: false },
      hazardMap:      { label: 'ハザードマップ',   url: 'https://www.city.ishikari.hokkaido.jp/kurashi/bosai/1005776/1004565/1002290.html', supportsLatLng: false, supportsAddress: false },
      firePrevention: { label: '防火・準防火地域', url: null, supportsLatLng: false, supportsAddress: false },
      waterSewer:     { label: '上下水道確認',     url: null, supportsLatLng: false, supportsAddress: false },
      culturalAssets: { label: '埋蔵文化財確認',  url: null, supportsLatLng: false, supportsAddress: false },
    },
  },
}

export function getMunicipalityLinks(muniCd) {
  return MUNICIPALITY_LINKS[muniCd] || null
}
